services:
  - type: web
    name: news-app
    env: node
    buildCommand: npm install && node build.cjs
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
